<?php


namespace rednaoeasycalculationforms\core\Managers\FormManager\Fields;


use rednaoeasycalculationforms\Utilities\Sanitizer;

class FBChainedField extends FBFieldWithPrice
{

    public function GetSelectedOptions(){
        if($this->Entry==null)
            return null;
        $selectedValues=Sanitizer::GetValueFromPath($this->Entry,['Value']);

        if(!is_array($selectedValues))
            return [];

        $values=[];
        foreach($selectedValues as $currentValue)
        {
            if(!is_scalar($currentValue))
                return [];

            $values[]=strval($currentValue);
        }

        return $values;

    }
    public function GetLineItems()
    {
        $item= parent::GetLineItems()[0];

        $options=$this->GetSelectedOptions();

        $itemList=array();
        $index=0;
        foreach($options as $currentOption)
        {
            $newItem=$item->CloneItem();
            $newItem->Value=$currentOption;
            $newItem->SubType=strval($index);

            $index++;
            $itemList[]=$newItem;
        }

        return $itemList; // TODO: Change the autogenerated stub
    }

    protected function InternalToText()
    {
        $items=$this->GetSelectedOptions();
        $columns=Sanitizer::GetValueFromPath($this->Options,['Columns']);

        if(!is_array($columns)||count($columns)!=count($items))
            return '';

        $text='';
        for($i=0;$i<count($items);$i++)
        {
            $text.=$columns[$i].': '.$items[$i]."\n";
        }

        return $text;
    }


}