<?php


namespace rednaoeasycalculationforms\core\Managers\FormManager\Fields;


class FBImagePicker extends FBMultipleOptionsField
{
    public function GetHTMLTemplate($context = null)
    {
        return 'core/Managers/FormManager/Fields/FBImagePicker.twig';
    }

    public function GetIconData($iconName)
    {
        return $this->GetForm()->GetIcon($iconName);

    }

    protected function InternalSanitize($sanitizer)
    {
        parent::InternalSanitize($sanitizer); // TODO: Change the autogenerated stub
        $item=$sanitizer->GetSanitizerByProperty('SelectedValues');
        if($item!=null)
            $item->Manager->AddIgnoreSanitizer("Icon",(Object)[],true);
    }

    protected function CanSanitize()
    {
        return true;
    }
}